### PR TITLE
Remote option

### PR DESCRIPTION
**Pull request by vyncem**
screen shot 2016-01-06 at 09 37 20
screen shot 2016-01-06 at 09 37 00

### CODE REVIEW

**Comment by theirishpenguin** [comment]
Looks good, thanks. Merge away and redeploy!

**Comment by vyncem** [comment]
Pushed to production - requiring a bit of [jiggery pokery](https://github.com/rubyireland/rubyjobs2/commit/f66436b5bac2ae2ac526cf23590079ca6342d7cd)
screen shot 2016-01-18 at 12 32 02

**Comment by testbrian** [comment]
Great job

**Comment by vyncem** [comment]
Cheers. Great job on the remote icon @testbrian I like how it looks.

**Pull request merged**
